### ISSUE TITLE
install should install and update according to the .lock

### ISSUE THREAD

**Issue by jhass** [ysbaddaden/shards#65]
Let's have a project and a library
```
$ tree
├── libs
│   └── library
│       └── shard.yml
├── shard.lock
└── shard.yml
$ cat shard.yml
name: "project"
version: 0.1.0
dependencies:
  library:
    git: ../../library
    branch: master
$ cat shard.lock
version: 1.0
shards:
  library:
    git: ../../library
    commit: 1c5d802a00011557294c15eef52f387a0d551f23
$ cd ..
$ git --git-dir=library/.git log --oneline -1
6b0b9e8 new file
```

Let's clone our project to install it somewhere else:
```
$ git clone project clone
$ cd clone
$ shards
Updating ../../library
Updating ../../library
Updating ../../library
Updating ../../library
Updating ../../library
Installing library (1c5d802a00011557294c15eef52f387a0d551f23)
Updating ../../library
Updating ../../library
$ tree
Updating ../../library
Updating ../../library
Updating ../../library
Updating ../../library
Updating ../../library
Installing library (1c5d802a00011557294c15eef52f387a0d551f23)
Updating ../../library
Updating ../../library
$ tree
.
├── libs
│   └── library
│       ├── library.cr
│       ├── new_file.cr
│       └── shard.yml
├── shard.lock
└── shard.yml
$  cat shard.lock
version: 1.0
shards:
  library:
    git: ../../library
    commit: 1c5d802a00011557294c15eef52f387a0d551f23
```
Okay, first bug, lock is still the same, output has claimed to install `1c5d802a`, actually installed is `6b0b9e8`.

Let's get rid of that `clone`, update the lock to `6b0b9e8` and clone and install again.
```
$ cd ..
$ rm -rf clone
$ cd project
$ shards
```
Mkay, we called install, lock stays the same but the worktree is the updated version again. But that's probably the same bug as above. Time to update the lock. Then let's clone our project again and install

```
$ shards update
$ git commit -am "update library"
$ cd ..
$ git clone project clone
$ cd clone
$ shards
```

Everything good so far. Time to fix something in the library.

```
$ cd ..
$ cd library
$ touch src/fix.cr
$ git add src
$ git commit -m "fix"
$ cd ../project
$ shards update
$ git commit -am "update library again"
$ cd ../clone
$ git pull
$ shards
Updating ../../library
Updating ../../library
Updating ../../library
Updating ../../library
Updating ../../library
Using library (94417f573623cce28f69d26fdf1dc09cccd75b2d)
$ tree
.
├── libs
│   └── library
│       ├── library.cr
│       ├── new_file.cr
│       └── shard.yml
├── shard.lock
└── shard.yml

2 directories, 5 files
```

And now we got the above bug in reverse, install claimed it installed `94417f5` but the worktree wasn't updated.

**Comment by ysbaddaden** [comment]
Oh, you actually hit a FIXME: https://github.com/ysbaddaden/shards/blob/464caddde295140ffd085c0894462e25235fc5a5/src/resolvers/git.cr#L54

**Comment by ysbaddaden** [comment]
Can you confirm this is fixed? Or do you still have bugs with locked commits? If so I'll release v0.5.3 and upload binaries, which would fix #69

**Comment by jhass** [comment]
Mmh, actually the second case still doesn't work, the worktree isn't updated:
```
$ cd clone
$ tree ../library/ ../project/
../library/
├── shard.yml
└── src
    ├── fix2.cr
    ├── fix.cr
    ├── library.cr
    ├── new_file2.cr
    └── new_file.cr
../project/
├── libs
│   └── library
│       ├── fix2.cr
│       ├── fix.cr
│       ├── library.cr
│       ├── new_file2.cr
│       ├── new_file.cr
│       └── shard.yml
├── shard.lock
└── shard.yml
$ git --git-dir "../library/.git" log --oneline -1
7a0376c fix 2
$ cat shard.lock
version: 1.0
shards:
  library:
    git: ../../library
    commit: 7a0376c65c81753a5d60b5af815fa370f0c4be80

$ shards
Updating ../../library
Updating ../../library
Updating ../../library
Using library (7a0376c65c81753a5d60b5af815fa370f0c4be80)
$ tree
.
├── libs
│   └── library
│       ├── fix.cr
│       ├── library.cr
│       ├── new_file.cr
│       └── shard.yml
├── shard.lock
└── shard.yml

**Comment by ysbaddaden** [comment]
Exact. Hopefully this is now fixed.

**Comment by jhass** [comment]
Well, you broke your testsuite :)

**Comment by jhass** [comment]
And I'm getting
```
$ cd clone
$ git pull
$ shards
Updating ../../library
Updating ../../library
Updating ../../library
Installing library ()
Updating ../../library
git command failed: git ls-tree -r --full-tree --name-only  -- shard.yml ()
```

**Comment by ysbaddaden** [comment]
```yaml
version: 1.0
shards:
  web:
    git: file:////home/julien/work/github/shards/test/.repositories/web
    commit: 
```

Seems like the broken test catched it. The sha1 is missing in the lock file.

**Comment by ysbaddaden** [comment]
Fixed? Maybe...

**Comment by jhass** [comment]
Looks good to me!

**Comment by ysbaddaden** [comment]
Cool!
